[package]
name = "dump-parser"
version = "0.9.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.1"
serde = "1.0"

crc = "1.8"
